name: pa_mobile_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  camera: ^0.11.0+2
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_vision: ^1.1.4
  gal: ^2.3.0
  http: ^1.2.2
  image: ^4.3.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/labels.txt
    - assets/best_float32.tflite
    - assets/best_float16.tflite

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
