// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdVkO4tMtTewd58CxoAIp7l56G3ilzyfU',
    appId: '1:529773918028:web:94e51150adfeef02e681e9',
    messagingSenderId: '529773918028',
    projectId: 'flutter-pa-3f338',
    authDomain: 'flutter-pa-3f338.firebaseapp.com',
    storageBucket: 'flutter-pa-3f338.firebasestorage.app',
    measurementId: 'G-73P1XPRWNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhmvAG8LaqvFsFgfIGZC1rFiNowId0U8k',
    appId: '1:529773918028:android:d7ec885665e937b1e681e9',
    messagingSenderId: '529773918028',
    projectId: 'flutter-pa-3f338',
    storageBucket: 'flutter-pa-3f338.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcJd7n9QSre2I6gmYPwyDar4kiqkghAfQ',
    appId: '1:529773918028:ios:c08c679fcb9ece29e681e9',
    messagingSenderId: '529773918028',
    projectId: 'flutter-pa-3f338',
    storageBucket: 'flutter-pa-3f338.firebasestorage.app',
    iosBundleId: 'com.example.paMobile1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcJd7n9QSre2I6gmYPwyDar4kiqkghAfQ',
    appId: '1:529773918028:ios:c08c679fcb9ece29e681e9',
    messagingSenderId: '529773918028',
    projectId: 'flutter-pa-3f338',
    storageBucket: 'flutter-pa-3f338.firebasestorage.app',
    iosBundleId: 'com.example.paMobile1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdVkO4tMtTewd58CxoAIp7l56G3ilzyfU',
    appId: '1:529773918028:web:e337e0dcb964f2bae681e9',
    messagingSenderId: '529773918028',
    projectId: 'flutter-pa-3f338',
    authDomain: 'flutter-pa-3f338.firebaseapp.com',
    storageBucket: 'flutter-pa-3f338.firebasestorage.app',
    measurementId: 'G-CT3KL96REE',
  );

}